module.exports = {
  mySidebar: [
    'index',
  {
    type: 'category',
    label: 'Unit 1',
    collapsed: true,
    items: [
      'SMA History',
      'Support Information',
      'Class Information',
      'Architecture',
      'Action Buttons',
      'OpCon Terminology',
      'Machines',
      'Schedule Master',
      'Unit 1 Exercise 1',
      'Batch Jobs',
      'Unit 1 Exercise 2',
      'Job Requirements',
      'Frequency Definition',
      'Unit 1 Exercise 3',
      'Dependencies',
      'Unit 1 Exercise 4',
      'Tags And Tag Manager',
      'Unit 1 Exercise 5',
      'Schedule Builds',
      'Unit 1 Exercise 6',
      'Operation Views',
      'Schedule Status',
      'Unit 1 Exercise 7',
      'Update Master Job',
      'Unit 1 Exercise 8',
      'OpCon Logs',
      'Solution Manager',
      'SM - Schedule Build',
      'SM - Job Processes',
      'SM - Job Status',
      'SM - Job Configuration',
      'SM - Diagrams And Views',
      'SM - Machine Status And User Accounts',
      'Unit 1 Exercise 9',
      'Workflow Designer',
      'Unit 1 Exercise 10',
      'Unit 1 Lab',
    ],
},
  {
    type: 'category',
    label: 'Unit 2',
    collapsed: true,
    items: [
      'Unit 1 Review',
      'Global Properties',
      'Unit 2 Exercise 1',
      'Null Jobs',
      'Unit 2 Exercise 2',
      'UNIX Jobs',
      'Unit 2 Exercise 3',
      'Unit 2 Exercise 4 And 5',
      'UNIX Job Details',
      'Unit 2 Exercise 6',
      'Job Dependency Types',
      'Calendars',
      'Unit 2 Exercise 7',
      'Frequency Definition Wizard',
      'All Weeks -- On Occurrence -- On Day',
      'Unit 2 Exercise 8',
      'On Request -- Periods',
      'Unit 2 Exercise 9',
      'On Interval -- Odd Even -- Annual Plan',
      'Unit 2 Exercise 10',
      'Other Frequency Details',
      'Looping Jobs',
      'Multiple Frequencies',
      'Unit 2 Exercise 11',
      'Unit 2 Lab A',
      'OpCon User Help',
      'Troubleshooting Schedules And Jobs',
      'Audit Management',
      'Server Options',
      'Unit 2 Lab B'
    ],
},
{
  type: 'category',
  label: 'Unit 3',
  collapsed: true,
  items: [
    'Unit 2 Review',
  ],
},
{
  type: 'category',
  label: 'Unit 4',
  collapsed: true,
  items: [
    'Unit 3 Review',
  ],
},
  {  
  type: 'link',
  label: 'Take OpCon Basic Training Exam',
  href: 'https://www.onlineexambuilder.com/opcon-basic-training-certification/exam-362330',
},
  ],
};
