module.exports = {
  mySidebar: [
    'index',
  {
    type: 'category',
    label: 'Unit 1',
    collapsed: true,
    items: [
      'SMA History',
      'Customer Support',
      'Customer Community',
      'OpCon Help',
      'Training Lab Information',
      'Architecture',
      'Solution Manager',
      'Action Buttons',
      'OpCon Terminology',
      'Schedule Master',
      'Unit 1 Exercise 1',
      'Batch Jobs',
      'Unit 1 Exercise 2',
      'Job Requirements',
      'Frequency Definition',
      'Unit 1 Exercise 3',
      'Dependencies',
      'Unit 1 Exercise 4',
      'Tags And Tag Manager',
      'Unit 1 Exercise 5',
      'Schedule Builds',
      'Operation Views',
      'Unit 1 Exercise 6',
      'Schedule Status',
      'Unit 1 Exercise 7',
      'Update Master Job',
      'Unit 1 Exercise 8',
      'OpCon Logs',
      'Troubleshooting Schedules And Jobs',
      'Unit 1 Lab',
    ],
  },
  {
    type: 'category',
    label: 'Unit 2',
    collapsed: true,
    items: [
      'Unit 1 Review',
      'Global Properties',
      'Unit 2 Exercise 1',
      'Null Jobs',
      'Unit 2 Exercise 2',
      'Agent Details',
      'Unit 2 Exercise 3',
      'Unit 2 Exercise 4 And 5',
      'UNIX Job Details',
      'Unit 2 Exercise 6',
      'Job Dependency Types',
      'Calendars',
      'Unit 2 Exercise 7',
      'Frequency Overview',
      'All Weeks -- On Occurrence -- On Day',
      'Unit 2 Exercise 8',
      'On Request -- Periods',
      'Unit 2 Exercise 9',
      'On Interval -- Annual Plan -- Odd Even',
      'Unit 2 Exercise 10',
      'Other Frequency Details',
      'Looping Jobs',
      'Unit 2 Exercise 11',
      'Multiple Frequencies',
      'Unit 2 Exercise 12',
      'Unit 2 Lab A',
      'Audit Management',
      'User Settings',
      'Server Options',
      'Unit 2 Lab B'
    ],
},
{
  type: 'category',
  label: 'Unit 3',
  collapsed: true,
  items: [
    'Unit 2 Review',
    'User Accounts and Role Management',
    'Unit 3 Exercise 1',
    'Privileges',
    'Unit 3 Exercise 2',
    'Batch Users',
    'Unit 3 Exercise 3',
    'Departments',
    'Unit 3 Exercise 4',
    'Schedule Privileges',
    'Unit 3 Exercise 5',
    'Access Codes',
    'Unit 3 Exercise 6',
    'Function Privileges',
    'Unit 3 Exercise 7',
    'Common Role Configurations',
    'Unit 3 Lab A',
    'Notification Manager',
    'Unit 3 Exercise 8',
    'Escalation Manager',
    'Unit 3 Exercise 9',
    'System Properties',
    'Unit 3 Exercise 10',
    'Job Instance Properties',
    'Schedule Instance Properties',
    'Machine Instance Properties',
    'Unit 3 Exercise 11',
    'Unit 3 Lab B',
    'OpCon Events',
    'Unit 3 Exercise 12',
    'Event Triggers',
    'Unit 3 Exercise 13',
    'Job Exit Description Events',
    'Advanced Failure Criteria',
    'Unit 3 Exercise 14',
    'Annual Plan Events',
    'Unit 3 Lab C'
  ],
},
{
  type: 'category',
  label: 'Unit 4',
  collapsed: true,
  items: [
    'Unit 3 Review',
    'Resources',
    'Unit 4 Exercise 1',
    'Thresholds',
    'Unit 4 Exercise 2',
    'External Event Thresholds',
    'Unit 4 Exercise 3',
    'Embedded Scripts',
    'Unit 4 Exercise 4',
    'Unit 4 Exercise 5',
    'Unit 4 Lab A',
    'SubSchedules and Container Jobs',
    'Unit 4 Exercise 6',
    'Unit 4 Exercise 7',
    'Unit 4 Exercise 8',
    'SMA File Transfer',
    'Unit 4 Exercise 9',
    'Windows File Movement Job Sub-Types',
    'Unit 4 Exercise 10',
    'Integrated File Watcher Job',
    'File Arrival Jobs',
    'Unit 4 Exercise 11',
    'Unit 4 Exercise 12',
    'Unit 4 Lab B'
  ],
},
{
  type: 'category',
  label: 'Self Service Module',
  collapsed: true,
  items: [
    'About Self Service',
    'Working in Admin Mode',
    'Defining A Request',
    'Stylizing Service Request Buttons',
    'Disabling And Hiding Requests',
    'Setting Up OpCon Events',
    'Setting Up User Inputs',
    'Setting Up Privileges',
    'Creating Categories',
    'User Mode',
    'Filtering And Querying',
    'Viewing Process Indicators',
    'Self Service Exercise 1',
    'Self Service Exercise 2',
    'Self Service Exercise 3',
    'Self Service Lab'
  ],
},
{
  type: 'category',
  label: 'Additional Resources',
  collapsed: true,
  items: [
    'EM_Walkthroughs',
    'Review Answers',
//    'EM_Walkthroughs_Alt',
  ],
},
//{  
//  type: 'link',
//  label: 'OpCon Basic Training Exam',
//  href: 'https://www.onlineexambuilder.com/opcon-basic-training-certification/exam-362330',
//},
{  
  type: 'link',
  label: 'Student Feedback Survey',
  href: 'https://forms.office.com/r/pQu8LwxYws',
},
  ],
};
